### ISSUE TITLE
Update Codeception to 2.2.1

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/gsoc16_browser-automated-tests#20]
@pritalpatel since Codeception 2.2.1 has been released (http://codeception.com/06-03-2016/codeception-2.2-is-here.html) you can send a pull request to change this line: https://github.com/joomla-projects/gsoc16_browser-automated-tests/blob/staging/tests/composer.json#L23 to:

   `"codeception/codeception": "~2.2",`

**Comment by pritalpatel** [comment]
OK javi, I will change it. :+1:

**Comment by yvesh** [comment]
Done by Prital
