### ISSUE TITLE
Blog Post for JCM

### ISSUE THREAD

**Issue by yvesh** [joomla-projects/gsoc16_browser-automated-tests#5]

**Comment by puneet0191** [comment]
@pritalpatel Please coordinate with Ana, You will have to get the Article reviewed by mentors once, before 25th and submit the Article in the Submission Bucket by 30th May.

**Comment by pritalpatel** [comment]
Thanks. I have shared doc with mentors.

**Comment by pritalpatel** [comment]
Submitted on JCM article bucket and waiting to publish JCM Jun edition.
