### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc16_browser-automated-tests#77]
I am quite new and tested the repository the first time today.
Thanks for the good explanation, everything worked better than I expected.
Only one point:
In the readme.md everything is described as
./tests
is the base directory.
But the
composer.json is in
./tests/codeception.

**Comment by yvesh** [comment]
Hello Astrid, 
first a big thanks for testing.

Pull Requests against the README are more then welcome :-)

Yves

P.S.: If you are insteresting in helping Joomla! with testing we can invite you to the Automated testing team. We have a meeting every three weeks and you can learn a lot on that topic (and have much fun).

**Comment by yvesh** [comment]
@astridx Merged your PR, is there anything left were we need to change the path or can you / we close this issue? :-)

**Comment by astridx** [comment]
Thank you. I noticed nothing else
